export const PRODUCT_CONSTANTS = {
  MAX_IMAGES_PER_PRODUCT: 10,
  MAX_VARIANTS_PER_PRODUCT: 20,
  MAX_SPECIFICATIONS_PER_PRODUCT: 30,
  MAX_TAGS_PER_PRODUCT: 15,

  IMAGE_SIZES: {
    THUMBNAIL: '100x100',
    SMALL: '300x300',
    MEDIUM: '600x600',
    LARGE: '1200x1200'
  },

  STOCK_STATUSES: {
    IN_STOCK: 'IN_STOCK',
    OUT_OF_STOCK: 'OUT_OF_STOCK',
    LOW_STOCK: 'LOW_STOCK'
  },

  LOW_STOCK_THRESHOLD: 5
};